name: flutter_myinsta
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.8
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/



  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf


